project:
  type: website
  output-dir: docs

website:
  title: "fun with stats"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: topics/manifesto_globe.qmd
        text: Parteifamilien


format:
  html:
    theme: cosmo
    toc: true
    lang: de
